openapi: "3.0.1"
info:
  title: "${api-name}"
  description: "API to orchestrate integration between Trello and Github"
  version: "1.0"
paths:
  /publish:
    post:
      summary: Publish some message into IoT topic
      description: |
        Publish some message into IoT topic
      x-amazon-apigateway-integration:
        type: aws
        passthroughBehavior: when_no_match
        uri: ${send_to_topic_lambda_arn}
        credentials: ${lambda_invoke_role_arn}
        httpMethod: POST
        requestTemplates:
          application/json: |
            #set($params = $input.path('$'))
            {
              "led": "$params.led",
              "state": $params.state,
              "timestamp": $context.requestTimeEpoch,
              "callbackUrl": "$context.domainName/$context.stage/lastHash"
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'*'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                #set($context.responseOverride.status = $input.path('$.statusCode'))
                #set($context.requestOverride.header.content-type = $input.path('$.contentType'))
                $input.path('$.body')
      responses:
        200:
          description: Success response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'*'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"

  /lastHash:
    post:
      summary: Update the last seen hash
      description: |
        Update the last seen hash
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          # echo requests as responses
          # https://stackoverflow.com/questions/47918477/aws-api-gateway-use-mock-integration-to-echo-response-body
          application/json: |
            #set($context.requestOverride.path.body = $input.body)
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'*'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                #set($context.responseOverride.status = $input.path('$.statusCode'))
                #set($body = $context.requestOverride.path.body)
                {
                  "echoRequest": $body
                }
      responses:
        200:
          description: Success response
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'*'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
